[versions]
activity = "1.3.1"
annotation = "1.3.0-alpha01"
appcompat = "1.4.0-alpha03"
browser = "1.3.0"
compose = "1.1.0-alpha02"
core = "1.7.0-alpha01"
datastore = "1.0.0"
lifecycle-compose = "1.0.0-alpha07"
lifecycle-core = "2.4.0-alpha03"
navigation = "2.4.0-alpha07"
paging-core = "3.1.0-alpha03"
paging-compose = "1.0.0-alpha12"
room = "2.4.0-alpha04"
work = "2.7.0-alpha05"

[libraries]
activity-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
activity-activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
annotation-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-materialIconsCore = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-uiUtil = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
core-coreKtx = { module = "androidx.core:core-ktx", version.ref = "core" }
datastore-datastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
lifecycle-commonJava8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle-core" }
lifecycle-livedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-core" }
lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-compose" }
lifecycle-viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-core" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
navigation-runtimeKtx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging-core" }
room-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
work-runtimeKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
